baseurl                  = "https://renner.github.io"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Johannes Hahn"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    # favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "&copy; 2020-2024 Johannes Hahn, based on [the sam theme](https://github.com/victoriadrake/hugo-theme-sam) for [Hugo](https://gohugo.io)."
    customCSS            = ["/css/custom.css"]

# Metadata for Open Graph and Twitter
    # description          = "A new Hugo site."               # Max 160 characters show in search results
    # images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    # title                = "Call me Sam"
    # rss                = ""

[[params.mainMenu]]
    link = "about"
    text = "about me"

[[params.mainMenu]]
    link = "photography"
    text = "photography"

[[params.mainMenu]]
    link = "projects"
    text = "projects"

[params.flickr]
    userId = ""
    apiKey = ""
